apiVersion: v1
kind: ReplicationController
metadata:
  name: product
  labels:
    name: product
spec:
  replicas: 1
  selector:
    name: product
  template:
    metadata:
      labels:
        name: product 
    spec:
      containers:
      - name: go-shopping-product
        image: danielbryantuk/go-shopping-product-v1
        ports:
        - containerPort: 3010
